// Code generated by scripts/relay-protocol-tool.py. DO NOT EDIT.
// Manual edits are forbidden; `make relay-protocol-check` rejects drift.
// Source-Schema: Protocol/Relay/relay-v1.schema.json
// Schema-SHA256: 3dd1bc9d8d0c1f9127cad05913137754da61d2657e8d0b8c0b30108e331e8000
// Generator-Format-Version: 1
// Regenerate: make relay-protocol-generate

// Package protocol carries the generated relay protocol v1 wire constants
// and typed metadata. Handwritten code must not restate these values.
//
// Semantics: TASK-260715-111tde (binding ADR) and TASK-260715-18owh7 (limits).
package protocol

type WireField struct {
	Name       string
	ByteOffset int
	ByteWidth  int
}

type NamedValue struct {
	Name  string
	Value uint64
}

type BitAssignment struct {
	Bit            int
	Name           string
	IsAllocated    bool
	ValidOnMessage string
	ValidDirection string
	GatedByFeature string
}

type MessageDirection string

const MessageDirectionClientToRelay MessageDirection = "clientToRelay"
const MessageDirectionRelayToClient MessageDirection = "relayToClient"
const MessageDirectionBoth MessageDirection = "both"

type AssociationIDRule string

const AssociationIDRuleZero AssociationIDRule = "zero"
const AssociationIDRuleNonzero AssociationIDRule = "nonzero"

type PayloadShape string

const PayloadShapeFixed PayloadShape = "fixed"
const PayloadShapeHEVUDPRecord PayloadShape = "hevUDPRecord"

type MessageMetadata struct {
	Type          MessageType
	Name          string
	Direction     MessageDirection
	AssociationID AssociationIDRule
	PayloadShape  PayloadShape
	// FixedPayloadWidth is the exact payload byte count for fixed shapes;
	// -1 for variable payloads.
	FixedPayloadWidth int
}

type AddressTypeMetadata struct {
	Type             AddressType
	Name             string
	IsLengthPrefixed bool
	MinAddressBytes  int
	MaxAddressBytes  int
}

type LimitClass string

const LimitClassNegotiatedWire LimitClass = "negotiatedWire"
const LimitClassFixedWireConstant LimitClass = "fixedWireConstant"
const LimitClassLocalCap LimitClass = "localCap"

type LimitSpec struct {
	Name              string
	Class             LimitClass
	ByteWidth         int
	Unit              string
	ClientDefault     uint64
	RelayDefault      uint64
	Floor             uint64
	ClientHardCeiling uint64
	RelayHardCeiling  uint64
}

type ReservedMessageTypeRange struct {
	First   uint8
	Last    uint8
	Purpose string
}

const ProtocolName = "relux-relay"
const WireVersion uint16 = 1
const ByteOrder = "big-endian"
const MagicASCII = "RLXR"

var Magic = [4]byte{0x52, 0x4C, 0x58, 0x52}

const SchemaSHA256 = "3dd1bc9d8d0c1f9127cad05913137754da61d2657e8d0b8c0b30108e331e8000"
const GeneratorFormatVersion = 1

var ClientHelloLayout = []WireField{
	{Name: "magic", ByteOffset: 0, ByteWidth: 4},
	{Name: "version", ByteOffset: 4, ByteWidth: 2},
	{Name: "flags", ByteOffset: 6, ByteWidth: 2},
	{Name: "maxFrame", ByteOffset: 8, ByteWidth: 4},
}

var ServerHelloLayout = []WireField{
	{Name: "magic", ByteOffset: 0, ByteWidth: 4},
	{Name: "version", ByteOffset: 4, ByteWidth: 2},
	{Name: "status", ByteOffset: 6, ByteWidth: 2},
	{Name: "features", ByteOffset: 8, ByteWidth: 4},
	{Name: "maxFrame", ByteOffset: 12, ByteWidth: 4},
}

const ClientHelloWidth = 12
const ServerHelloWidth = 16

type HelloStatus uint16

const HelloStatusAccepted HelloStatus = 0x0000
const HelloStatusUnsupportedVersion HelloStatus = 0x0001
const HelloStatusInvalidClientHello HelloStatus = 0x0002
const HelloStatusResourcePolicyRejected HelloStatus = 0x0003
const HelloStatusRelayUnavailable HelloStatus = 0x0004

var HelloStatusNames = []NamedValue{
	{Name: "ACCEPTED", Value: 0},
	{Name: "UNSUPPORTED_VERSION", Value: 1},
	{Name: "INVALID_CLIENT_HELLO", Value: 2},
	{Name: "RESOURCE_POLICY_REJECTED", Value: 3},
	{Name: "RELAY_UNAVAILABLE", Value: 4},
}

const HelloFlagDNSPriorityHint uint16 = 0x0001
const HelloFlagsReservedMask uint16 = 0xFFFE

var HelloFlagAssignments = []BitAssignment{
	{Bit: 0, Name: "dnsPriorityHint", IsAllocated: true, ValidOnMessage: "", ValidDirection: "", GatedByFeature: ""},
	{Bit: 1, Name: "resourceLimitExchange", IsAllocated: false, ValidOnMessage: "", ValidDirection: "", GatedByFeature: ""},
}

const FeatureDNSPriorityHint uint32 = 0x00000001
const FeaturesReservedMask uint32 = 0xFFFFFFFE

var FeatureAssignments = []BitAssignment{
	{Bit: 0, Name: "dnsPriorityHint", IsAllocated: true, ValidOnMessage: "", ValidDirection: "", GatedByFeature: ""},
	{Bit: 1, Name: "resourceLimitExchange", IsAllocated: false, ValidOnMessage: "", ValidDirection: "", GatedByFeature: ""},
}

const FramePrefixWidth = 4
const EnvelopeHeaderWidth = 6
const EnvelopeLengthCoverage = "type-through-payload"
const MinFrameLength uint32 = 6
const MaxLegalFrameBody uint32 = 1733

var EnvelopeLayout = []WireField{
	{Name: "frameLength", ByteOffset: 0, ByteWidth: 4},
	{Name: "type", ByteOffset: 4, ByteWidth: 1},
	{Name: "flags", ByteOffset: 5, ByteWidth: 1},
	{Name: "associationID", ByteOffset: 6, ByteWidth: 4},
}

const EnvelopeFlagDNSPriority uint8 = 0x01
const EnvelopeFlagsReservedMask uint8 = 0xFE

var EnvelopeFlagAssignments = []BitAssignment{
	{Bit: 0, Name: "dnsPriority", IsAllocated: true, ValidOnMessage: "UDP_DATAGRAM", ValidDirection: "clientToRelay", GatedByFeature: "dnsPriorityHint"},
}

type MessageType uint8

const MessageTypeUDPDatagram MessageType = 0x10
const MessageTypeUDPError MessageType = 0x11
const MessageTypePing MessageType = 0x20
const MessageTypePong MessageType = 0x21
const MessageTypeCloseAssociation MessageType = 0x30
const MessageTypeCloseSession MessageType = 0x31

var MessageMetadataTable = []MessageMetadata{
	{Type: MessageTypeUDPDatagram, Name: "UDP_DATAGRAM", Direction: MessageDirectionBoth, AssociationID: AssociationIDRuleNonzero, PayloadShape: PayloadShapeHEVUDPRecord, FixedPayloadWidth: -1},
	{Type: MessageTypeUDPError, Name: "UDP_ERROR", Direction: MessageDirectionRelayToClient, AssociationID: AssociationIDRuleNonzero, PayloadShape: PayloadShapeFixed, FixedPayloadWidth: 2},
	{Type: MessageTypePing, Name: "PING", Direction: MessageDirectionClientToRelay, AssociationID: AssociationIDRuleZero, PayloadShape: PayloadShapeFixed, FixedPayloadWidth: 8},
	{Type: MessageTypePong, Name: "PONG", Direction: MessageDirectionRelayToClient, AssociationID: AssociationIDRuleZero, PayloadShape: PayloadShapeFixed, FixedPayloadWidth: 8},
	{Type: MessageTypeCloseAssociation, Name: "CLOSE_ASSOCIATION", Direction: MessageDirectionBoth, AssociationID: AssociationIDRuleNonzero, PayloadShape: PayloadShapeFixed, FixedPayloadWidth: 0},
	{Type: MessageTypeCloseSession, Name: "CLOSE_SESSION", Direction: MessageDirectionBoth, AssociationID: AssociationIDRuleZero, PayloadShape: PayloadShapeFixed, FixedPayloadWidth: 0},
}

var ReservedMessageTypeRanges = []ReservedMessageTypeRange{
	{First: 0x40, Last: 0x4F, Purpose: "resource-governance"},
}

type AddressType uint8

const AddressTypeIPv4 AddressType = 0x01
const AddressTypeDomain AddressType = 0x03
const AddressTypeIPv6 AddressType = 0x04

var AddressTypeMetadataTable = []AddressTypeMetadata{
	{Type: AddressTypeIPv4, Name: "IPV4", IsLengthPrefixed: false, MinAddressBytes: 4, MaxAddressBytes: 4},
	{Type: AddressTypeDomain, Name: "DOMAIN", IsLengthPrefixed: true, MinAddressBytes: 1, MaxAddressBytes: 248},
	{Type: AddressTypeIPv6, Name: "IPV6", IsLengthPrefixed: false, MinAddressBytes: 16, MaxAddressBytes: 16},
}

var HEVFixedPrefixLayout = []WireField{
	{Name: "MSGLEN", ByteOffset: 0, ByteWidth: 2},
	{Name: "HDRLEN", ByteOffset: 2, ByteWidth: 1},
	{Name: "ATYP", ByteOffset: 3, ByteWidth: 1},
}

const HEVHeaderBaseWidth = 6
const HEVPortWidth = 2
const HEVHDRLENIPv4 = 10
const HEVHDRLENIPv6 = 22
const HEVHDRLENDomainBase = 7
const MinDomainWireBytes = 1
const MaxDomainWireBytes = 248
const MaxHEVRecordWidth = 1727

type UDPErrorCode uint16

const UDPErrorCodeInvalidDatagram UDPErrorCode = 0x0001
const UDPErrorCodeUnsupportedAddress UDPErrorCode = 0x0002
const UDPErrorCodeUnknownOrClosedAssociation UDPErrorCode = 0x0003
const UDPErrorCodeAssociationLimit UDPErrorCode = 0x0004
const UDPErrorCodeDatagramTooLarge UDPErrorCode = 0x0005
const UDPErrorCodeQueueSaturated UDPErrorCode = 0x0006
const UDPErrorCodeResolutionFailure UDPErrorCode = 0x0007
const UDPErrorCodeSocketFailure UDPErrorCode = 0x0008
const UDPErrorCodeIdleExpiry UDPErrorCode = 0x0009
const UDPErrorCodeResourceLimit UDPErrorCode = 0x000A

var UDPErrorCodeNames = []NamedValue{
	{Name: "INVALID_DATAGRAM", Value: 1},
	{Name: "UNSUPPORTED_ADDRESS", Value: 2},
	{Name: "UNKNOWN_OR_CLOSED_ASSOCIATION", Value: 3},
	{Name: "ASSOCIATION_LIMIT", Value: 4},
	{Name: "DATAGRAM_TOO_LARGE", Value: 5},
	{Name: "QUEUE_SATURATED", Value: 6},
	{Name: "RESOLUTION_FAILURE", Value: 7},
	{Name: "SOCKET_FAILURE", Value: 8},
	{Name: "IDLE_EXPIRY", Value: 9},
	{Name: "RESOURCE_LIMIT", Value: 10},
}

var Limits = []LimitSpec{
	{Name: "aggregateQueuedBytes", Class: LimitClassLocalCap, ByteWidth: 4, Unit: "bytes", ClientDefault: 1048576, RelayDefault: 4194304, Floor: 65536, ClientHardCeiling: 4194304, RelayHardCeiling: 16777216},
	{Name: "controlReservedBytes", Class: LimitClassLocalCap, ByteWidth: 4, Unit: "bytes", ClientDefault: 16384, RelayDefault: 65536, Floor: 4096, ClientHardCeiling: 262144, RelayHardCeiling: 262144},
	{Name: "dnsPriorityWeight", Class: LimitClassLocalCap, ByteWidth: 1, Unit: "ratioToOne", ClientDefault: 4, RelayDefault: 4, Floor: 1, ClientHardCeiling: 16, RelayHardCeiling: 16},
	{Name: "idleTimeout", Class: LimitClassLocalCap, ByteWidth: 4, Unit: "milliseconds", ClientDefault: 60000, RelayDefault: 120000, Floor: 10000, ClientHardCeiling: 600000, RelayHardCeiling: 600000},
	{Name: "maxAssociations", Class: LimitClassLocalCap, ByteWidth: 4, Unit: "count", ClientDefault: 256, RelayDefault: 256, Floor: 1, ClientHardCeiling: 1024, RelayHardCeiling: 1024},
	{Name: "maxFrame", Class: LimitClassNegotiatedWire, ByteWidth: 4, Unit: "bytes", ClientDefault: 4096, RelayDefault: 4096, Floor: 2048, ClientHardCeiling: 65536, RelayHardCeiling: 65536},
	{Name: "maxUDPPayload", Class: LimitClassFixedWireConstant, ByteWidth: 2, Unit: "bytes", ClientDefault: 1472, RelayDefault: 1472, Floor: 512, ClientHardCeiling: 1472, RelayHardCeiling: 1472},
	{Name: "perAssociationQueuedBytes", Class: LimitClassLocalCap, ByteWidth: 4, Unit: "bytes", ClientDefault: 32768, RelayDefault: 65536, Floor: 4096, ClientHardCeiling: 262144, RelayHardCeiling: 262144},
}

const AggregateQueuedBytesClientDefault uint32 = 1048576
const AggregateQueuedBytesRelayDefault uint32 = 4194304
const AggregateQueuedBytesFloor uint32 = 65536
const AggregateQueuedBytesClientHardCeiling uint32 = 4194304
const AggregateQueuedBytesRelayHardCeiling uint32 = 16777216
const ControlReservedBytesClientDefault uint32 = 16384
const ControlReservedBytesRelayDefault uint32 = 65536
const ControlReservedBytesFloor uint32 = 4096
const ControlReservedBytesClientHardCeiling uint32 = 262144
const ControlReservedBytesRelayHardCeiling uint32 = 262144
const DNSPriorityWeightClientDefault uint8 = 4
const DNSPriorityWeightRelayDefault uint8 = 4
const DNSPriorityWeightFloor uint8 = 1
const DNSPriorityWeightClientHardCeiling uint8 = 16
const DNSPriorityWeightRelayHardCeiling uint8 = 16
const IdleTimeoutClientDefault uint32 = 60000
const IdleTimeoutRelayDefault uint32 = 120000
const IdleTimeoutFloor uint32 = 10000
const IdleTimeoutClientHardCeiling uint32 = 600000
const IdleTimeoutRelayHardCeiling uint32 = 600000
const MaxAssociationsClientDefault uint32 = 256
const MaxAssociationsRelayDefault uint32 = 256
const MaxAssociationsFloor uint32 = 1
const MaxAssociationsClientHardCeiling uint32 = 1024
const MaxAssociationsRelayHardCeiling uint32 = 1024
const MaxFrameClientDefault uint32 = 4096
const MaxFrameRelayDefault uint32 = 4096
const MaxFrameFloor uint32 = 2048
const MaxFrameClientHardCeiling uint32 = 65536
const MaxFrameRelayHardCeiling uint32 = 65536
const MaxUDPPayloadClientDefault uint16 = 1472
const MaxUDPPayloadRelayDefault uint16 = 1472
const MaxUDPPayloadFloor uint16 = 512
const MaxUDPPayloadClientHardCeiling uint16 = 1472
const MaxUDPPayloadRelayHardCeiling uint16 = 1472
const PerAssociationQueuedBytesClientDefault uint32 = 32768
const PerAssociationQueuedBytesRelayDefault uint32 = 65536
const PerAssociationQueuedBytesFloor uint32 = 4096
const PerAssociationQueuedBytesClientHardCeiling uint32 = 262144
const PerAssociationQueuedBytesRelayHardCeiling uint32 = 262144

const MaxFrameDefault uint32 = 4096
const MaxFrameHardCeiling uint32 = 65536
const MaxUDPPayload uint16 = 1472
const MaxUDPPayloadLocalFloor uint16 = 512

// ParityLines is the canonical language-neutral rendering of every value
// above. The Swift and Go parity tests re-derive these lines from the typed
// metadata and fail on any hand edit; make relay-protocol-check compares
// bytes.
var ParityLines = []string{
	"protocol name=relux-relay wireVersion=1 byteOrder=big-endian magic=RLXR",
	"helloField peer=client name=magic offset=0 width=4",
	"helloField peer=client name=version offset=4 width=2",
	"helloField peer=client name=flags offset=6 width=2",
	"helloField peer=client name=maxFrame offset=8 width=4",
	"helloField peer=server name=magic offset=0 width=4",
	"helloField peer=server name=version offset=4 width=2",
	"helloField peer=server name=status offset=6 width=2",
	"helloField peer=server name=features offset=8 width=4",
	"helloField peer=server name=maxFrame offset=12 width=4",
	"helloWidth client=12 server=16",
	"envelopeField name=frameLength offset=0 width=4",
	"envelopeField name=type offset=4 width=1",
	"envelopeField name=flags offset=5 width=1",
	"envelopeField name=associationID offset=6 width=4",
	"envelope prefixWidth=4 headerWidth=6 lengthCoverage=type-through-payload minFrameLength=6 maxLegalFrameBody=1733",
	"helloStatus name=ACCEPTED value=0",
	"helloStatus name=UNSUPPORTED_VERSION value=1",
	"helloStatus name=INVALID_CLIENT_HELLO value=2",
	"helloStatus name=RESOURCE_POLICY_REJECTED value=3",
	"helloStatus name=RELAY_UNAVAILABLE value=4",
	"helloFlagBit bit=0 name=dnsPriorityHint status=allocated validOnMessage=- validDirection=- gatedByFeature=-",
	"helloFlagBit bit=1 name=resourceLimitExchange status=reserved validOnMessage=- validDirection=- gatedByFeature=-",
	"helloFlagsReservedMask value=65534",
	"featureBit bit=0 name=dnsPriorityHint status=allocated validOnMessage=- validDirection=- gatedByFeature=-",
	"featureBit bit=1 name=resourceLimitExchange status=reserved validOnMessage=- validDirection=- gatedByFeature=-",
	"featuresReservedMask value=4294967294",
	"envelopeFlagBit bit=0 name=dnsPriority status=allocated validOnMessage=UDP_DATAGRAM validDirection=clientToRelay gatedByFeature=dnsPriorityHint",
	"envelopeFlagsReservedMask value=254",
	"messageType name=UDP_DATAGRAM value=16 direction=both association=nonzero payload=hevUDPRecord fixedPayloadWidth=-1",
	"messageType name=UDP_ERROR value=17 direction=relayToClient association=nonzero payload=fixed fixedPayloadWidth=2",
	"messageType name=PING value=32 direction=clientToRelay association=zero payload=fixed fixedPayloadWidth=8",
	"messageType name=PONG value=33 direction=relayToClient association=zero payload=fixed fixedPayloadWidth=8",
	"messageType name=CLOSE_ASSOCIATION value=48 direction=both association=nonzero payload=fixed fixedPayloadWidth=0",
	"messageType name=CLOSE_SESSION value=49 direction=both association=zero payload=fixed fixedPayloadWidth=0",
	"reservedMessageTypeRange first=64 last=79 purpose=resource-governance",
	"addressType name=IPV4 value=1 lengthPrefixed=false min=4 max=4",
	"addressType name=DOMAIN value=3 lengthPrefixed=true min=1 max=248",
	"addressType name=IPV6 value=4 lengthPrefixed=false min=16 max=16",
	"hevField name=MSGLEN offset=0 width=2",
	"hevField name=HDRLEN offset=2 width=1",
	"hevField name=ATYP offset=3 width=1",
	"hev headerBaseWidth=6 portWidth=2 hdrlenIPv4=10 hdrlenIPv6=22 hdrlenDomainBase=7 minDomainWireBytes=1 maxDomainWireBytes=248 maxRecordWidth=1727",
	"udpErrorCode name=INVALID_DATAGRAM value=1",
	"udpErrorCode name=UNSUPPORTED_ADDRESS value=2",
	"udpErrorCode name=UNKNOWN_OR_CLOSED_ASSOCIATION value=3",
	"udpErrorCode name=ASSOCIATION_LIMIT value=4",
	"udpErrorCode name=DATAGRAM_TOO_LARGE value=5",
	"udpErrorCode name=QUEUE_SATURATED value=6",
	"udpErrorCode name=RESOLUTION_FAILURE value=7",
	"udpErrorCode name=SOCKET_FAILURE value=8",
	"udpErrorCode name=IDLE_EXPIRY value=9",
	"udpErrorCode name=RESOURCE_LIMIT value=10",
	"limit name=aggregateQueuedBytes class=localCap width=4 unit=bytes clientDefault=1048576 relayDefault=4194304 floor=65536 clientHardCeiling=4194304 relayHardCeiling=16777216",
	"limit name=controlReservedBytes class=localCap width=4 unit=bytes clientDefault=16384 relayDefault=65536 floor=4096 clientHardCeiling=262144 relayHardCeiling=262144",
	"limit name=dnsPriorityWeight class=localCap width=1 unit=ratioToOne clientDefault=4 relayDefault=4 floor=1 clientHardCeiling=16 relayHardCeiling=16",
	"limit name=idleTimeout class=localCap width=4 unit=milliseconds clientDefault=60000 relayDefault=120000 floor=10000 clientHardCeiling=600000 relayHardCeiling=600000",
	"limit name=maxAssociations class=localCap width=4 unit=count clientDefault=256 relayDefault=256 floor=1 clientHardCeiling=1024 relayHardCeiling=1024",
	"limit name=maxFrame class=negotiatedWire width=4 unit=bytes clientDefault=4096 relayDefault=4096 floor=2048 clientHardCeiling=65536 relayHardCeiling=65536",
	"limit name=maxUDPPayload class=fixedWireConstant width=2 unit=bytes clientDefault=1472 relayDefault=1472 floor=512 clientHardCeiling=1472 relayHardCeiling=1472",
	"limit name=perAssociationQueuedBytes class=localCap width=4 unit=bytes clientDefault=32768 relayDefault=65536 floor=4096 clientHardCeiling=262144 relayHardCeiling=262144",
}

const ParitySHA256 = "da2d6bb55d6609f7a70ef872cc440b4826b2881aed2024684ac934cfdb2a2164"
